version: "3.8"

services:
  excalidraw-storage-backend:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      STORAGE_URI: redis://redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"
